(function() {var implementors = {};
implementors['has'] = [];implementors['quandl_v3'] = ["impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;ApiArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DatabaseSearch.html' title='quandl_v3::prelude::DatabaseSearch'>DatabaseSearch</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;SearchArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DatabaseSearch.html' title='quandl_v3::prelude::DatabaseSearch'>DatabaseSearch</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;ApiArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DatasetSearch.html' title='quandl_v3::prelude::DatasetSearch'>DatasetSearch</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;SearchArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DatasetSearch.html' title='quandl_v3::prelude::DatasetSearch'>DatasetSearch</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;ApiArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DatabaseMetadataQuery.html' title='quandl_v3::prelude::DatabaseMetadataQuery'>DatabaseMetadataQuery</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;ApiArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DatasetMetadataQuery.html' title='quandl_v3::prelude::DatasetMetadataQuery'>DatasetMetadataQuery</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;ApiArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.CodeListQuery.html' title='quandl_v3::prelude::CodeListQuery'>CodeListQuery</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;DataArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DataQuery.html' title='quandl_v3::prelude::DataQuery'>DataQuery</a>","impl <a class='trait' href='has/trait.HasMut.html' title='has::HasMut'>HasMut</a>&lt;ApiArguments&gt; for <a class='struct' href='quandl_v3/prelude/struct.DataQuery.html' title='quandl_v3::prelude::DataQuery'>DataQuery</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
